config/routes.rb
Rails.application.routes.draw do
  root to:'books#index' 
  get '/login',to:'sessions#new'
  post '/login',to:'sessions#create'
  delete '/logout',to:'sessions#destroy'
  resources 'users'
  
  
  resources 'books' do
    collection do
    get :mine
  end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates :title,presence: true
    validates :implession,length: {maximum: 200}
    
    mount_uploader :img,AvatarUploader
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    
    validates :name,presence:true
    validates :email,presence:true, uniqueness: true
    
    has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
    before_action :login_required
    
    private
    def current_user
        @current_user ||=User.find_by(id: session[:user_id])if session[:user_id]
    end
    
    def login_required
        redirect_to login_url unless current_user
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book,only:[:edit,:update,:destroy]
  skip_before_action :login_required,only:[:index]
  def index
    @books=Book.all.order(created_at: :desc)
  end
  
  def mine
    @books=current_user.books.order(created_at: :desc)
    @user=current_user
  end

  def show
    @book=Book.find(params[:id])
    @user=current_user
  end

  def new
    @book=Book.new
  end
  
  def create
    @book=current_user.books.new(book_parameter)
    if @book.save
      redirect_to books_path,notice:"ツイートしました"
    else
      render :new
    end
  end

  def edit
  end
  
  def update
    if @book.update(book_parameter)
      redirect_to @book
    else
      render :new,notice:"ツイートを編集"
    end
  end
  
  def destroy
    @book.destroy
    redirect_to @book,notice:"ツイートを削除"
  end
  
  private
  def book_parameter
    params.require(:book).permit(:title,:implession,:img,:remove_img)
  end
  
  def set_book
    @book=current_user.books.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required
  
  def new
  end
  
  def create
    user=User.find_by(email: session_params[:email])
    if user&.authenticate(session_params[:password])
      session[:user_id]=user.id
      redirect_to root_url,notice:"ログインしました"
    else
      render :new
    end
  end
  
  def destroy
    reset_session
    redirect_to root_url,notice:"ログアウトしました"
  end
  
  private
  def session_params
    params.require(:session).permit(:email,:password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required,only:[:new,:create]
  before_action :user_set,only:[:index,:show,:edit,:update,:destroy]
  def new
    @user=User.new
  end
  
  def create
    @user=User.new(user_params)
    if @user.save
      redirect_to user_url(@user),notice:"ユーザー名「#{@user.name}さん」のプロフィールを更新しました。"
    else
      render :new,notice:"失敗しました。"
    end
  end

  def edit
  end
  
  def update
    if @user.update(user_params)
      redirect_to @user,notice:"ユーザー名「#{@user.name}さん」のプロフィールをを更新しました。"
    else
      render :edit
    end    
  end

  def show
  end

  def index
  end
  
  def destroy
    
  end
  
  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
  def user_set
    @user=current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%if @book.errors.present?%>
<ul>
    <%@book.errors.full_messages.each do |message|%>
    <li>message</li>
    <%end%>
</ul>
<%end%>
<%=form_with model:@book do |f|%>
    <%=f.label :title%><br>
    <%=f.text_field :title%><br><br>
    <%=f.label :implession%><br>
    <%=f.text_area :implession%><br>
    <%= f.label :img %>
    <%= f.file_field :img, id: :book_img %>
    <%= f.check_box :remove_img %>画像を削除する
    <br>
    <%=f.submit"登録する"%>
<%end%>

app/views/books/_table.html.erb
    
<!-- Note a custom script is used to activate toasts:
$('.toast').toast();
-->
    <%@books.each do |book|%>
<div class="toast fade show" role="alert" aria-live="assertive" aria-atomic="true">
  <div class="toast-header">
    <strong class="mr-auto"><%=link_to book.title, book%></strong>
    
    <small><%=book.created_at%></small>
    <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
    </button>
  </div>
  <%= image_tag book.img.url %>
  <div class="toast-body">
    <%=book.implession%>
  </div>
</div>
    <%end%>

app/views/books/edit.html.erb
<h1>編集</h1>

<%=render "form"%>

app/views/books/index.html.erb
<%=render "table"%>
    

app/views/books/mine.html.erb
<li><%=link_to "ユーザー情報",@user %></li>
<br>

<%=render "table"%>

app/views/books/new.html.erb
<h1>新規作成</h1>

<%=render "form"%>

app/views/books/show.html.erb
    <table>
        
        <%=@book.title%>
        <%=@book.implession%>
        <%= image_tag @book.img.url %>
        <% if logger? && @book.user == current_user%>
            <%=link_to "編集", edit_book_path(@book)%>
            <%=link_to "削除", @book,method: :delete, data:{confirm: "投稿を削除しますよろしいですか？"}%>
        <%end%>
    </table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookImplessions</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page"><%=link_to "一覧", books_path%></li>
    <%if current_user%>
    <li class="breadcrumb-item"><a href="#"><%=link_to "新規投稿", new_book_path%></a></li>
    <li class="breadcrumb-item"><a href="#"><%=link_to "プロフィール", mine_books_path%></a></li>
    <li class="breadcrumb-item active" aria-current="page"><%=link_to "ログアウト", logout_path,method: :delete%></li>
  <%else%>
    <li class="breadcrumb-item"><a href="#"><%=link_to "ログイン",login_path%></a></li>
    <li class="breadcrumb-item"><a href="#"><%=link_to "ユーザー新規登録",new_user_path%></a></li>  
  </ol>
</nav>
  <%end%>
  
<% flash.each do |key, value| %>
    <p class="alert alert-<%= key %>">
      <%= value %>
    </p>
<% end %>
  </header>
  <body>

    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%=form_with model:@user,local: true do |f|%>
    <%=f.label :name%>
    <%=f.text_field :name%>
    <%=f.label :email%>
    <%=f.text_field :email%>
    <%=f.label :password%>
    <%=f.text_field :password%>
    <%=f.label :password_confirmation%>
    <%=f.text_field :password_confirmation%>
    <%=f.submit%>
<%end%>

app/views/users/edit.html.erb
<h1>プロフィール編集</h1>
<%=render "form"%>

app/views/users/index.html.erb
<h1>ログイン</h1>
<%=link_to "ログイン",new_user_path%>
cc
<!--その人の投稿-->

<li><%=link_to "プロフィール", user_path(@user)%></li>

app/views/users/new.html.erb
<h1>ユーザー登録</h1>
<%=render "form"%>

app/views/users/show.html.erb
<h1>プロフィール</h1>

<table>
    <%=link_to "my一覧", mine_books_url%>
    <%=@current_user.name%><br>
    <%=@current_user.email%><br>
        <%=link_to "編集", edit_user_path(@current_user)%>
        <%=link_to "削除", @current_user,method: :delete, data:{confirm: "投稿を削除しますよろしいですか？"}%>
</table>